osuosl/streamwebs

.github/PULL_REQUEST_TEMPLATE.md
We have been using a pull request template in IAM for a while now (thanks @ElijahCaine for introducing that). I was skeptical at first but it is extremely helpful, especially for including the steps necessary to test the PR. As a reviewer who isn't actively working on the codebase, I would love to see this.
@leian7 @athai @Kennric
=> Add Github PR Template

README.md, streamwebs_frontend/streamwebs/admin.py, streamwebs_frontend/streamwebs/models.py, streamwebs_frontend/streamwebs/tests.py, streamwebs_frontend/streamwebs/tests/models/test_site_model.py
Fixes issue #16.
1. Start up an instance of the StreamWebs docker container
2. Log into the container w/ ``docker-compose run web bash``
3. ``cd`` into /streamwebs_frontend
4. Run ``python manage.py test streawebs/tests/models`` 
```
(venv) [root@390b322ed535 streamwebs_frontend]# python manage.py test streamwebs/tests/models/
....
Ran 4 tests in 0.002s
OK
```
=> Sites Model

streamwebs_frontend/streamwebs/admin.py, streamwebs_frontend/streamwebs/models.py, streamwebs_frontend/streamwebs/tests/models/test_macroinvert.py, streamwebs_frontend/streamwebs/tests/models/test_site_model.py
fixes issue #45 
1. Run ``docker-compose run web bash`` to open up a bash shell
2. cd into streamwebs_frontend/
3. Run ``python manage.py test streamwebs/tests/models`` to run the model tests. Alternatively, you can also run ``python manage.py test streamwebs/tests/*`` to run all the tests!
All tests:
```
[root@548a3563b829 streamwebs_frontend]# python manage.py test streamwebs/tests/*
...........................Invalid login details: notjohn, badpassword
.....<ul class="errorlist"><li>username<ul class="errorlist"><li>This field is required.</li></ul></li><li>password<ul class="errorlist"><li>This field is required.</li></ul></li></ul> <ul …
```
=> Macroinvertebrate Model

streamwebs_frontend/streamwebs/models.py
fixes issue #70 
1. Run docker-compose run web bash
2. cd into streamwebs_frontend
3. Run python manage.py test streamwebs/tests/models
1. Run docker-compose up
2. Go to http://localhost:8000/streamwebs/ 
3. Try bad birth date 
If the user inputs bad year, month or day, you will get the same error message. 
@leian7 @Kennric
=> Changed error message

.travis.yml, streamwebs_frontend/streamwebs/templates/streamwebs/base.html, streamwebs_frontend/streamwebs/templates/streamwebs/index.html, streamwebs_frontend/streamwebs/templates/streamwebs/login.html, streamwebs_frontend/streamwebs/templates/streamwebs/register.html, streamwebs_frontend/streamwebs/templates/streamwebs/sites.html
fixes issue #86
1. flake8
3. docker-compose up
Ran 11 tests in 0.388s
OK
@osuosl/devs
=> Made the index.html, register.html, login.html use base template

streamwebs_frontend/streamwebs/admin.py, streamwebs_frontend/streamwebs/models.py, streamwebs_frontend/streamwebs/tests/models/test_canopy_cover.py, streamwebs_frontend/streamwebs/tests/models/test_cc_cardinal.py, streamwebs_frontend/streamwebs/tests/models/test_site_model.py, streamwebs_frontend/streamwebs/tests/models/test_water_quality.py
fixes issue #62 
1. ``docker-compose run web bash``
2. ``cd`` streamwebs_frontend/
3. ``python manage.py test streamwebs/models/tests``
```
[root@4d703ed1cfdc streamwebs_frontend]# python manage.py test streamwebs/tests/models/
...............................
Ran 31 tests in 0.506s
OK
```
=> Canopy Cover Survey Model

runtests.sh
fixes issue #108 
1. docker-compose run web bash
```
.......................................................Invalid login details: notjohn, badpassword
.....<ul class="errorlist"><li>password<ul class="errorlist"><li>Passwords do not match</li></ul></li></ul> 
.<ul class="errorlist"><li>username<ul class="errorlist"><li>This field is required.</li></ul></li><li>password_check<ul class="errorlist"><li>This field is required.</li></ul></li><li>password<ul class="errorlist"><li>This field …
```
=> Creates a test DB once resulting in faster tests

streamwebs_frontend/streamwebs/forms.py
fixes issue #107 
1. docker-compose run web bash
```
.......................................................Invalid login details: notjohn, badpassword
.....<ul class="errorlist"><li>password<ul class="errorlist"><li>Passwords do not match</li></ul></li></ul> 
.<ul class="errorlist"><li>username<ul class="errorlist"><li>This field is required.</li></ul></li><li>password_check<ul class="errorlist"><li>This field is required.</li></ul></li><li>password<ul class="errorlist"><li>This field …
```
=> Removed duplicate password field in forms.py

streamwebs_frontend/streamwebs/forms.py, streamwebs_frontend/streamwebs/tests/forms/test_wq_form.py
fixes issue #103
1. flake8
....................................................
Ran 52 tests in 0.388s
OK
...
Ran 3 tests in 0.009s
OK
.Invalid login details: notjohn, badpassword
.Invalid login details: …
=> Water quality forms and test

streamwebs_frontend/streamwebs/models.py, streamwebs_frontend/streamwebs/tests/models/test_schools.py
fixes issue #122 
1. `./runtests.sh`
```
$ make test
```
@osuosl/devs
=> First draft of schools model

streamwebs_frontend/streamwebs/tests/models/test_user_model.py
fixes issue #xx
1. Do `./runtest.sh`
```
$ make test
```
@osuosl/devs
=> fix birthdate test

data_scripts/get_sites.py
1. ``docker-compose run web bash``
2. ``./runtests.sh``
3. ``cd data_scripts``, ``./get_sites.py``
```
[root@a190f8486c65 streamwebs]# ./runtests.sh 
........................................................................................................................................
Ran 136 tests in 5.784s
OK
```
Also, maps should be displaying a valid location on the Django admin panel.
@Kennric @leian7 @alxngyn @LyonesGamer @subnomo
=> Fix sites import script

streamwebs_frontend/streamwebs/admin.py, streamwebs_frontend/streamwebs/models.py, streamwebs_frontend/streamwebs/tests/models/test_schools.py, streamwebs_frontend/streamwebs/tests/models/test_site_model.py, streamwebs_frontend/streamwebs/tests/models/test_soil_survey.py
Fixes #132 
1. Run `docker-compose run web bash`
2. Run `./runtests.sh`
```
[root@49ec1d816137 streamwebs]# ./runtests.sh 
.........................................................................................Invalid login details: notjohn, badpassword
..........<ul class="errorlist"><li>password<ul class="errorlist"><li>Passwords do not match</li></ul></li></ul> 
.<ul class="errorlist"><li>username<ul class="errorlist"><li>This field is required.</li></ul></li><li>password_check<ul …
```
=> Soil Survey Model

data_scripts/get_users.py
fixes issue #156 
1. Do `docker-compose run web bash`.
2. Do `cd data_scripts`.
3. `./get_sites.py` then `./get_schools.py` then `./get_users.py`
4. See all data get loaded with `dbshell` or admin panel
```
[root@62eb1ad0985a data_scripts]# get_sites
bash: get_sites: command not found
[root@62eb1ad0985a data_scripts]# ./get_sites.py 
Data loaded.
[root@62eb1ad0985a data_scripts]# ./get_schools.py 
Data loaded.
[root@62eb1ad0985a data_scripts]# ./get_users.py   
Data loaded.
[root@62eb1ad0985a data_scripts]# 
```
@osuosl/devs
=> get_users.py fix

data_scripts/get_macros.py, streamwebs_frontend/streamwebs/static/streamwebs/js/graphs/macros.js
fixes issue #157 
1. Do `docker-compose up`
2. hit `http://localhost:8000/streamwebs/sites/greasy-creek/macros/` 
3. look at time graph
```
$ ./runtests # should pass
```
@osuosl/devs
=> fixed macros data migration

streamwebs_frontend/streamwebs/static/streamwebs/js/graphs/macros.js
Fixes #170.
1. Visit the macro graph page for a site with lots of macro data (I might recommend Shafer Creek).
A graph which accurately shows the data with the elements listed above, such as:
@osuosl/devs
=> Make line graph linear, add data points, condense points to 1 per day.

data_scripts/get_sites.py, requirements.txt, streamwebs_frontend/streamwebs_frontend/settings.py.dist
Fixes #177.
1. Run collectstatic.
No errors.
@osuosl/devs
=> Remove django-pipeline.

streamwebs_frontend/streamwebs/models.py, streamwebs_frontend/streamwebs/static/streamwebs/js/graphs/water_quality.js, streamwebs_frontend/streamwebs/templates/streamwebs/graphs/water_quality.html, streamwebs_frontend/streamwebs/views.py
1. Create or input test data for water quality.
2. Go to `localhost:8000/sites/<site_slug>/water`.
Graph page with headlines.
@osuosl/devs
=> Create graphs for water quality data.

streamwebs_frontend/streamwebs/static/streamwebs/js/sites.js
Missing brackets makes it so the sites page doesn't display a map.
1. Do docker.
2. View sites page
The map and site markers should display correctly.
=> Add missing brackets

streamwebs_frontend/streamwebs/tests/views/test_index_view.py, streamwebs_frontend/streamwebs/urls.py, streamwebs_frontend/streamwebs/views.py, streamwebs_frontend/streamwebs_frontend/urls.py
Fix url namespacing for staging deployment.
1. ``docker-compose run web bash``
2. ``./runtests.sh``
```
[root@260f2c75acdd streamwebs]# ./runtests.sh 
..................................................................................................................................................................................
Ran 178 tests in 7.651s
OK
```
URL formatting has changed from ``localhost:8000/streamwebs/<site-slug>`` to ``localhost:8000/<site-slug>``
=> URL changes

streamwebs_frontend/streamwebs/forms.py, streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/riparian_transect_edit.html, streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/water_quality.html, streamwebs_frontend/streamwebs/tests/forms/test_wq_form.py, streamwebs_frontend/streamwebs/tests/views/test_rip_transect_edit_view.py, streamwebs_frontend/streamwebs/tests/views/test_water_quality_edit_view.py, streamwebs_frontend/streamwebs/tests/views/test_water_quality_view_view.py
Fixes point 3 of #187.
1. Try to add a WQ datum.
2. Try to add a Riparian Transect datum.
Both sheets will contain a working school dropdown.
@osuosl/devs
=> Change 'School' field to dropdown in WQ and Riparian Transect forms.

streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/camera_point_add.html, streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/canopy_cover_edit.html, streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/macroinvertebrate_edit.html, streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/photo_point_add.html, streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/riparian_transect_edit.html, streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/soil_edit.html, streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/water_quality.html, streamwebs_frontend/streamwebs/templates/streamwebs/login.html, streamwebs_frontend/streamwebs/templates/streamwebs/register.html
Fixes #202 
2. Visit http://localhost:8000/login
3. Log in
You should then log in correctly, rather than encountering an error.
@osuosl/devs
=> Replace bare links with django url function

streamwebs_frontend/streamwebs/templates/streamwebs/register.html
fixes issue #187 
1. Do look at register page.
2. See only one schools dropdown.
```
$ make test
[... should pass ...]
```
@osuosl/devs
=> fixed schools on register page

streamwebs_frontend/streamwebs/forms.py, streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/riparian_transect_edit.html, streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/riparian_transect_view.html, streamwebs_frontend/streamwebs/tests/views/test_rip_transect_view_view.py
Fixes issue #199. Dependent on #196. 
1. Do docker
2. ``python streamwebs_frontend/manage.py streamwebs_frontend/streamwebs/tests/*``
3. ``cd data_scripts`` then run ``./get_all.sh`` to migrate data
In browser:
1. ``docker-compose up``
2. Select a site (Hesthavn Nature Center has a few data sheets) and view existing sheets
3. Additionally,  create a new data sheet to test that everything works properly
```
[root@8a0f65563263 streamwebs]# python streamwebs_frontend/manage.py test streamwebs_frontend/streamwebs/tests/*
......................................................................................................................................................................................... …
```
=> Materialze Riparian Transect

streamwebs_frontend/streamwebs/models.py, streamwebs_frontend/streamwebs/templates/streamwebs/graphs/macroinvertebrates.html, streamwebs_frontend/streamwebs/templates/streamwebs/graphs/water_quality.html, streamwebs_frontend/streamwebs/templates/streamwebs/site_detail.html, streamwebs_frontend/streamwebs/urls.py
Fixes #181.
1. `docker-compose run`
2. Visit a page for a site with water quality and macroinvertebrate data
3. Click on the water quality graph
There will be a section with links to the WQ and Macro graphs, and the WQ graph header will be fixed.
@osuosl/devs
=> Add graph links and fix WQ graph header.

streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/camera_point_add.html
Fixes #207.
2. Add a camera point to a site.
The site dropdown won't be present, but the form will still have the correct site on the view page.
@osuosl/devs
=> Remove the site dropdown from the Camera Point edit sheet.

streamwebs_frontend/streamwebs/models.py, streamwebs_frontend/streamwebs/static/streamwebs/js/graphs/water_quality.js, streamwebs_frontend/streamwebs/templates/streamwebs/graphs/water_quality.html
According to Renee's requests at the last meeting.
2. Look at WQ graphs for a site like Cox Creek.
It should be in two columns and able to be set.
@osuosl/devs
=> Move to two-column water quality graphs with hiding.

streamwebs_frontend/streamwebs/templates/streamwebs/register.html
Fix #236.
2. Register for an account
You *won't* get an invalid date error.
@osuosl/devs
=> Change date format to remove errors.

streamwebs_frontend/streamwebs/static/streamwebs/style.css, streamwebs_frontend/streamwebs/templates/streamwebs/base.html, streamwebs_frontend/streamwebs/templates/streamwebs/graphs/macroinvertebrates.html, streamwebs_frontend/streamwebs/templates/streamwebs/graphs/water_quality.html, streamwebs_frontend/streamwebs/templates/streamwebs/navigation.html
1. Go to a page like the WQ graphs
2. Click the link in the header
It takes you back to the site detail page.
@osuosl/devs
=> Make the header links work.

streamwebs_frontend/streamwebs/static/streamwebs/js/graphs/water_quality.js
Fixes #253.
2. Visit http://localhost:8000/sites/se-belmont/water/, and mess around with the time scales.
The labels should be rotated, and text should no longer overlap regardless of how dense the ticks are.
@osuosl/devs
=> Rotate x-axis labels by 45 degrees.

streamwebs_frontend/streamwebs/static/streamwebs/js/graphs/macros.js, streamwebs_frontend/streamwebs/templates/streamwebs/graphs/macroinvertebrates.html
Same as #254 but for the time graph of macroinvertebrates.
2. See http://localhost:8000/sites/shafer-creek/macros/, mess with the time scales to get ticks closer or farther apart.
X-axis labels should be rotated 45 degrees and not overlap.
@osuosl/devs
=> Rotate labels on macroinvertebrate graph.

streamwebs_frontend/streamwebs/forms.py, streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/camera_point_add.html, streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/camera_point_view.html, streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/photo_point_add.html, streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/photo_point_view.html, streamwebs_frontend/streamwebs/tests/forms/test_photopoint_form.py, streamwebs_frontend/streamwebs/tests/views/test_camerapoint_add.py, streamwebs_frontend/streamwebs/tests/views/test_camerapoint_view.py, streamwebs_frontend/streamwebs/tests/views/test_photopoint_add.py, streamwebs_frontend/streamwebs/views/general.py
fixes issue #200 
1. Do `docker-compose up`.
2. Do look at a camera photo point add page and make one
3. Do look at a camera photo point view page of the abomination you made
4. Do look at the photo point detail page of from the camera point view page
5. Do Try to edit a photo point page 
9000. test em all.
SSs coming soon ... 
@osuosl/devs
=> Materialize camera photo point forms

streamwebs_frontend/streamwebs/static/streamwebs/style.css, streamwebs_frontend/streamwebs/templates/streamwebs/base.html, streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/camera_point_add.html, streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/camera_point_view.html, streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/canopy_cover_edit.html, streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/canopy_cover_view.html, streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/macroinvertebrate_edit.html, streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/macroinvertebrate_view.html, streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/photo_point_view.html, streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/riparian_transect_edit.html, streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/riparian_transect_view.html, streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/soil_edit.html, streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/soil_view.html, streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/water_quality.html, streamwebs_frontend/streamwebs/templates/streamwebs/index.html, streamwebs_frontend/streamwebs/templates/streamwebs/navigation.html, streamwebs_frontend/streamwebs/tests/views/test_photopoint_view.py
Fixes #247.
2. Visit the index page, and a few others.
With language as normal:
The best I could do to shrink the language selection:
@osuosl/devs
=> Update CSS to clean up the site.

streamwebs_frontend/streamwebs/static/streamwebs/js/graphs/macros.js, streamwebs_frontend/streamwebs/static/streamwebs/js/graphs/water_quality.js, streamwebs_frontend/streamwebs/templates/streamwebs/graphs/water_quality.html
Based on meeting on 2017-04-26.
2. See http://localhost:8000/sites/se-belmont/water/
All of the above changes should be apparent.
@osuosl/devs
=> Remove graph lines, recolor, average by day, add mouseover, add histogram functionality.

streamwebs_frontend/streamwebs/static/streamwebs/js/graphs/water_quality.js, streamwebs_frontend/streamwebs/static/streamwebs/js/graphs/wq_histogram.js, streamwebs_frontend/streamwebs/templates/streamwebs/graphs/water_quality.html, streamwebs_frontend/streamwebs/templates/streamwebs/graphs/wq_histogram.html, streamwebs_frontend/streamwebs/urls.py, streamwebs_frontend/streamwebs/views/general.py
Based on the meeting with Renee on 2017-04-26.
2. http://localhost:8000/sites/se-belmont/water/
3. Click a data point on any graph
The histogram should have reasonable ranges and be accurate to the data.
@osuosl/devs
=> Add the histogram when the user clicks a WQ data point.

streamwebs_frontend/streamwebs/templates/streamwebs/sites.html
fixes issue #257 
1. Open site.html
2. See if link to create_site exist
1. Link to create_site exist
```
$ make test
```
@osuosl/devs
=> Added create_site link in site.html

streamwebs_frontend/streamwebs/management/commands/gendata.py, streamwebs_frontend/streamwebs/views/general.py
The script creates a site to hold a large amount of dummy testing data for use in testing other views such as graphs.
***WARNING: This script generates a LOT of data. Consider this, to an extent, a stress test on Streamwebs. Do NOT run on the staging or production servers. Only run locally.***
1. `docker-compose run web bash`
2. `manage.py makemigrations` and `manage.py migrate` if necessary
3. `manage.py gendata`
Creating site `data-test`...
Generating Water Quality data...
Generating Macroinvertebrate data...
Generating Canopy Cover data...
Generating Riparian Transect data...
Generating Soil Survey data...
Data generated.
Note that because of the high volume of data being created, the script may take a few minutes to run. Afterwards, you can `docker-compose up` and visit …
=> Create a manage.py command to generate lots of testing data.

streamwebs_frontend/streamwebs/templates/streamwebs/site_detail.html
fixes issue #295 
1. Added id to site_detail image.
1. Go to any site_detail, see if data_sheets are displayed
1. Data sheets are displayed
```
$ make test
```
@osuosl/devs
=> Fixed image id in site_detail.html, working properly

streamwebs_frontend/streamwebs/forms.py, streamwebs_frontend/streamwebs/static/streamwebs/js/site_detail.js, streamwebs_frontend/streamwebs/templates/streamwebs/create_site.html, streamwebs_frontend/streamwebs/templates/streamwebs/site_detail.html, streamwebs_frontend/streamwebs/templates/streamwebs/sites.html, streamwebs_frontend/streamwebs/tests/views/test_create_site_view.py, streamwebs_frontend/streamwebs/tests/views/test_retrieve_site.py, streamwebs_frontend/streamwebs/views/general.py
=> Revert "Maps in Site Detail are functional"

streamwebs_frontend/streamwebs/static/streamwebs/js/graphs/water_quality.js, streamwebs_frontend/streamwebs/templates/streamwebs/graphs/water_quality.html
fixes issue #283
1. Go to water quality site.
2. Uncheck all checks until only one graph is checked, see if graph is responsive (bigger width and height).
1. Graph is responsive
```
$ make test
```
@osuosl/devs
=> Responsive water quality graph

streamwebs_frontend/streamwebs/static/streamwebs/js/graphs/water_quality.js, streamwebs_frontend/streamwebs/static/streamwebs/style.css, streamwebs_frontend/streamwebs/templates/streamwebs/graphs/water_quality.html, streamwebs_frontend/streamwebs/views/general.py
fixes issue #302 #303 #304 #317 #324 
1. navigate to sites/se-belmont/water
2. resize the window, see if the graph is always single column
3. see if there are data that are 0 (There are some that appear to be 0, but they are value very close to 0 that got rounded to 0)
4. hover on one of the data point, see if tooltip shows, hover on another one, see if the old one disappear. Click on random spot on the graph (not tooltip or the data point) See if tooltip disappear.
5. Hover on graph title, see if a div show up with normal range of data.
6. Add a random site to compare, see if the graphs are aligned in 2 columns.
7. Click on the search dropdown, see if there are sites with no data (no water quality graph), compare with sites.html to see the difference.
8. Clear the site 2 by clicking …
=> Improve water quality graph

data_scripts/get_users.py
emergency fix for user import found during staging deploy
1. Do X.
2. Do Y.
3. See Z.
```
$ make test
```
@osuosl/devs
=> default blank firt/last names

streamwebs_frontend/streamwebs/fixtures/data_sheets.json, streamwebs_frontend/streamwebs/fixtures/publications.json, streamwebs_frontend/streamwebs/fixtures/tutorial_videos.json, streamwebs_frontend/streamwebs/models.py
fixes issue #307 
1. Switch to my branch
2. Docker-compose up
3. Navigate to resources
4. Check that resources are there
```
Resources are there
```
@osuosl/devs
=> Upload Resources

streamwebs_frontend/streamwebs/static/streamwebs/js/graphs/water_quality.js, streamwebs_frontend/streamwebs/templates/streamwebs/graphs/water_quality.html
fixes issue #319 
1. Navigate to a site water quality
2. Use new fancy search bar instead of the drop down
3. Try selecting a different site, clearing and re-searching
```
I searched up a site and it works
```
@osuosl/devs
=> Searchable Sites in Water Quality Graphs

streamwebs_frontend/streamwebs/static/streamwebs/style.css, streamwebs_frontend/streamwebs/templates/streamwebs/site_detail.html
fixes issue #342 
1. Navigate to site_detail
2. see map
```
That's a map alright
```
@osuosl/devs
=> fixing site_detail map to show

streamwebs_frontend/streamwebs/templates/streamwebs/create_site.html
1. Create site
2. See the map is back
3. Rejoice
```
Maps are back 
```
@osuosl/devs
=> fixed create site css issues from the front end fix

streamwebs_frontend/streamwebs/templates/streamwebs/sites.html
fixes issue #383 
1. Go to Sites Page, see that it's at the top
```
How does he do it?
```
@osuosl/devs
=> moved create site button to the top

streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/camera_point_add.html, streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/camera_point_view.html, streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/canopy_cover_edit.html, streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/macroinvertebrate_edit.html, streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/photo_point_view.html, streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/riparian_transect_edit.html, streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/soil_edit.html, streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/water_quality.html, streamwebs_frontend/streamwebs/templates/streamwebs/site_detail.html
fixes issue #365 
1. Nav to site, add new data
2. See the dropdown says new camera point
3. See the indicators on Date fields, and compass bearing, and camera height
4. Add a camera point, check that fields have units
```
$ make test
```
@osuosl/devs
=> Correct Terminology Around Camera/Photo Points

streamwebs_frontend/streamwebs/fixtures/tutorial_videos.json, streamwebs_frontend/streamwebs/templates/streamwebs/resources/resources_tutorial_videos.html
fixes issue my issue
1. Don't do much
```
$ make test
```
@osuosl/devs
=> Staging site resource video fix

streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/camera_point_add.html, streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/canopy_cover_edit.html, streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/macroinvertebrate_edit.html, streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/riparian_transect_edit.html, streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/soil_edit.html, streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/water_quality.html
1. Add datasheet to school
2. See the add school/org button
3. Rejoice
```
Who is he
```
@osuosl/devs
=> Added school button to all datasheets

streamwebs_frontend/streamwebs/models.py
fixes issue on staging hopefully
1. Redeploy Staging After merge
2. Hope tutorial videos page is working and not broken
```
$ make test
```
@osuosl/devs
=> Added Helper method to resource video model

streamwebs_frontend/streamwebs/fixtures/tutorial_videos.json
fixes issue #xx
1. Do X.
2. Do Y.
3. See Z.
```
$ make test
```
@osuosl/devs
=> updated fixtures

streamwebs_frontend/streamwebs/templates/streamwebs/site_detail.html
fixes issue #395 
1. Log in as non admin
2. Nav to site
3. See if you can edit it
```
$ make test
```
@osuosl/devs
=> Logged in users can edit sites, Not only admin

streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/camera_point_view.html
fixes issue #399 
1. Nav to site, and a camera point datasheet
2. See that location has longitude and latitude
```
Who is he
```
@osuosl/devs
=> Added latitude to camera point view

streamwebs_frontend/streamwebs/templates/streamwebs/resources.html
fixes issue #420 (nice)
1. Navigate to resources
2. Check out those 2 new resources, make sure spelling is good and that they take you to the right page
3. Rejoice
```
$ make test
```
@osuosl/devs
=> Added Resources, Changed blurbs for another

streamwebs_frontend/streamwebs/templates/registration/password_reset_done.html
fixes issue #432 
Fixes the typos on the password reset page.
@osuosl/devs
=> Corrected the typos

streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/canopy_cover_edit.html, streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/macroinvertebrate_edit.html, streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/photo_point_add.html, streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/rip_aqua_edit.html, streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/riparian_transect_edit.html, streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/soil_edit.html, streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/water_quality_edit.html
fixes issue #436 
1. Go to a datasheet
2. Hit enter key
3. Be amazed that nothing happens
```
$ make test
```
@osuosl/devs
=> Disabled enter key on all datasheet edits

streamwebs_frontend/streamwebs/forms.py, streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/rip_aqua_edit.html
fixes issue #408 
1. Add a school from any datasheet or from the create account page
2. See that the school is in the correct spot in the dropdown by name
```
$ make test
```
@osuosl/devs
=> sorted all schools in drop downs by name

streamwebs_frontend/streamwebs_frontend/settings.py.dist
=> Set uploaded files to 644 so that nginx can read it on production

streamwebs_frontend/streamwebs/fixtures/data_sheets.json, streamwebs_frontend/streamwebs/media/assets/Macros_SW_Spanish.pdf, streamwebs_frontend/streamwebs/media/assets/WaterQuality_SW_Spanish.pdf, streamwebs_frontend/streamwebs/media/assets/thumbnails/Macroinvertebrates_Spanish.png, streamwebs_frontend/streamwebs/media/assets/thumbnails/WQ_Spanish.png, streamwebs_frontend/streamwebs/templates/streamwebs/resources.html
fixes issue #idk
1. go to resource page
2. check out new resources
3. Be happy.
```
$ make test
```
@osuosl/devs
=> added 3 new resources like renee asked. tut vids -> vernier tut vids, Oh and spanish

streamwebs_frontend/streamwebs/fixtures/data_sheets.json
```
$ make test
```
@osuosl/devs
=> spanish macroinvertebrates -> spanish Aquatic macroinvertebrates

dockerfiles/Dockerfile, streamwebs_frontend/streamwebs/templates/streamwebs/faq.html, streamwebs_frontend/streamwebs/templates/streamwebs/index.html, streamwebs_frontend/streamwebs/templates/streamwebs/navigation.html, streamwebs_frontend/streamwebs/urls.py, streamwebs_frontend/streamwebs/views/general.py
fixes issue #476 
1. Go to home page
2. Look at banner
3. Click on banner
4. Have your questions resolved
```
$ make test
```
@osuosl/devs
=> Add FAQ Page

streamwebs_frontend/streamwebs/templates/streamwebs/index.html
I had some external feedback and suggested these changes to make it better for
users.
=> Clarify sections on frontpage

streamwebs_frontend/streamwebs/fixtures/sample_users.json
This fixes #524, at least in the short term by updating the data fixture which
includes a date. A better long term solution should be devised which dynamically
sets these dates so that no matter when we run this, it should work as intended.
=> Fix unit test for stats test

data_scripts/get_soil.py
We're actually doing a calculation in this script which returns a long float
number. When you use that number, it doesn't match what's in the database which
is a 2 decimal point number. So this limits it to 2 points and also converts it
to a string to ensure it matches what we should find in the production.
Also include notes for matching purposes.
This should finally fix #507 properly!
See #528 for how to test this.
=> Convert distance to a 2 decimal point stright in get_soil.py

streamwebs_frontend/streamwebs/views/export.py
fixes #538
1. ``docker-compose kill && docker-compose rm --all`` -- remove all old instances
1. ``docker-compose up -d postgres_host && sleep 10 && docker-compose up -d web``
1. A complete datasheet should be successfully downloaded when visiting http://localhost:8000/sites/se-belmont/rip_aqua/export/
=> corrected the fields in the export function for rip aqua

streamwebs_frontend/streamwebs/forms.py, streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/macroinvertebrate_view.html, streamwebs_frontend/streamwebs/templates/streamwebs/graphs/water_quality.html, streamwebs_frontend/streamwebs/views/general.py
Contains hotfixes for editing accounts without changing emails and new org registration.
=> Bug fix jan2017

streamwebs_frontend/streamwebs/static/streamwebs/js/graphs/macros.js, streamwebs_frontend/streamwebs/templates/streamwebs/graphs/macroinvertebrates.html
fixes issue #496 
1. Checkout a macro graph
2. See the fixes above
```
$ make test
```
@osuosl/devs
=> Macro Graph Fixes

streamwebs_frontend/streamwebs/templates/streamwebs/register.html
fixes issue #634 
1. See if message is present in register page
1. Register message is present in register page
```
$ make test
```
@osuosl/devs
=> Added register message

streamwebs_frontend/streamwebs/views/export.py
fixes issue #519 
1. Log in as a user with an associated school.
2. Go to a site and download one of the export files.
The file should contain the datasheets from every school that has provided data
=> Exports: Revert user school logic

streamwebs_frontend/streamwebs/models.py
fixes issue #651
1. Log in as superuser (or admin)
2. Go to localhost:8000/admin
3. Delete a random school. 
4. Check if any server errors occur
5. If no server errors occur, check if the school is deactivated in database.
1. No server error
2. The school is deleted.
```
$ make test
```
@osuosl/devs
=> Fixes Server 500 when school is deleted

streamwebs_frontend/streamwebs/static/streamwebs/js/graphs/wq_histogram.js
fixes issue #660
1. Go to any test sites, and click on all points on water quality graphs. See if histogram data matches.
1. Histogram is present, and the data is correct
@osuosl/devs
=> Changed code to calculate sample averages

streamwebs_frontend/streamwebs/forms.py, streamwebs_frontend/streamwebs/templates/streamwebs/register.html
fixes issue with ignored CAPTCHAs
1. Set up web server
2. Navigate to register page
3. Submit registration without CAPTCHA
4. Submit registration with CAPTCHA
5. Wait
Submission without CAPTCHA should fail. Human submission with CAPTCHA should succeed. Spam bots should not be able to submit.
@osuosl/devs
=> Fix for ignored CAPTCHA

streamwebs_frontend/streamwebs/forms.py, streamwebs_frontend/streamwebs/templates/streamwebs/register.html
fixes issue with ignored CAPTCHAs
1. Set up web server
2. Navigate to register page
3. Submit registration without CAPTCHA
4. Submit registration with CAPTCHA
5. Wait
Submission without CAPTCHA should fail. Human submission with CAPTCHA should succeed. Spam bots should not be able to submit.
@osuosl/devs
=> Captcha Fix
