streamwebs_frontend/streamwebs/models.py
streamwebs_frontend/streamwebs/tests/models/test_macroinvert.py

fixes issue #78 
documentation on Model.clean() here: https://docs.djangoproject.com/en/1.9/ref/models/instances
1.     docker-compose run web bash
2.     cd streamwebs_frontend
3.     python manage.py test streamwebs/tests/models
```
................................
Ran 32 tests in 0.322s
OK
```
@osuosl/devs

cthalmann/macroValidator Added .clean() method and tests.

---

streamwebs_frontend/streamwebs_frontend/settings.py.dist

fixes issue #97
1. Flake8
```
./runtests.sh
....................................
Ran 36 tests in 0.335s
OK
..
Ran 2 tests in 0.005s
OK
.Invalid login details: notjohn, badpassword
.Invalid login details: …
```

use the language names in local formats

---

streamwebs_frontend/streamwebs/forms.py
streamwebs_frontend/streamwebs/tests/forms/test_user_reg_form.py
streamwebs_frontend/streamwebs/tests/views/test_registration_view.py

To run tests:
1. Run docker-compose run web bash to open up an interactive shell
2. Cd to streamwebs_frontend
3. Run python manage.py test streamwebs/tests/forms and python manage.py test streamwebs/tests/views
To see in action:
1. Run docker-compose up
2. Go to http://localhost:8000/streamwebs/ and click "register"
```
..
Ran 2 tests in 0.005s
OK
.Invalid login details: notjohn, badpassword
.....<ul class="errorlist"><li>password<ul class="errorlist"><li>Passwords do not match</li></ul></li></ul> 
.<ul class="errorlist"><li>username<ul …
```

add password-reenter check for registration

---

streamwebs_frontend/streamwebs/forms.py
streamwebs_frontend/streamwebs/tests/forms/test_wq_form.py

Travis broke b/c of a naming inconsistency. This fixes the differences in forms/form tests so that migrations can be run.
1. Open the interactive shell
2. ``./runtests.sh``
```
[root@aa5a0a54ca31 streamwebs]# ./runtests.sh 
................./usr/lib/python2.7/site-packages/django/db/models/fields/__init__.py:1453: RuntimeWarning: DateTimeField RiparianTransect.date_time received a naive datetime (2016-07-11 14:09:00) while time zone support is active.
RuntimeWarning)
.............................................Invalid login details: notjohn, badpassword
.Invalid login details: notjohn, …
```

Change field name to be consistent w/ model

---

streamwebs_frontend/streamwebs/models.py
streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/riparian_transect_view.html
streamwebs_frontend/streamwebs/tests/models/test_canopy_cover.py
streamwebs_frontend/streamwebs/tests/models/test_macroinvert.py
streamwebs_frontend/streamwebs/tests/models/test_rip_transect.py
streamwebs_frontend/streamwebs/tests/models/test_site_model.py
streamwebs_frontend/streamwebs/tests/models/test_transect_zone.py
streamwebs_frontend/streamwebs/tests/models/test_water_quality.py
streamwebs_frontend/streamwebs/tests/models/test_wq_sample.py
streamwebs_frontend/streamwebs/tests/views/test_macro_edit.py
streamwebs_frontend/streamwebs/tests/views/test_macro_view.py
streamwebs_frontend/streamwebs/tests/views/test_rip_transect_edit_view.py
streamwebs_frontend/streamwebs/tests/views/test_rip_transect_view_view.py
streamwebs_frontend/streamwebs/urls.py
streamwebs_frontend/streamwebs/views.py

fixes issue #133
1 - You'll probably need to migrate your database to apply any changes to models.py:
```
$ docker-compose run web bash
```
2 - Run tests using `# ./runtests`
3 - Check flake8 using `# flake8`
```
./docs/source/conf.py:284:1: E265 block comment should start with '# '
( lots of these)
./streamwebs_frontend/streamwebs/migrations/0001_initial.py:27:80: E501 line too long (114 > 79 characters)
( lots of these)
```
You should not see any flake8 warnings except for `docs/source/conf.py` and `streamwebs_frontend/streamwebs/migrations/*`.
``` …
```

Convert views from using site_id to site_slug

---

dockerfiles/Dockerfile.env.dist

Fixes #153
1. Add `print("HELLO!")` to `streamwebs_frontend/streamwebs/__init__.py`
2. Run `docker-compose up`
```
subnomo@ultraviolet:~/Documents/streamwebs$ docker-compose up
Starting streamwebs_postgres_host_1
Starting streamwebs_web_1
Attaching to streamwebs_postgres_host_1, streamwebs_web_1
postgres_host_1  | LOG:  database system was shut down at 2016-09-22 22:48:33 UTC
postgres_host_1  | LOG:  MultiXact member wraparound protections are now enabled
postgres_host_1  | LOG:  database system is ready to accept connections
postgres_host_1  | LOG:  autovacuum launcher started
web_1            | HELLO!
web_1            | HELLO!
web_1            | Performing system checks...
web_1            | 
web_1            | System check identified no issues (0 silenced).
web_1            | September …
```

Allow prints in docker

---

streamwebs_frontend/streamwebs/static/streamwebs/js/sites.js
streamwebs_frontend/streamwebs/templates/streamwebs/graphs/water_quality.html

Fixes #168.
1. See the /sites/ endpoint
2. See a page showing a water quality graph for a site.
1. The /sites/ endpoint should now have a working dropdown, working search bar, and working info windows when you click on a marker in the map
2. The water quality graph should now properly show the site name in the header.
@osuosl/devs

Fix pages that use site names or slugs incorrectly.

---

streamwebs_frontend/streamwebs/static/streamwebs/js/sites.js
streamwebs_frontend/streamwebs/templates/streamwebs/sites.html

Fixes #172.
1. Visit the sites page
1. The search bar should no longer have checkboxes, and should display all matching sites
2. The map should display all markers as red
@osuosl/devs

Removed site types from sites page.

---

streamwebs_frontend/streamwebs/static/streamwebs/js/sites.js

fixes issue #183 
1. Do docker.
2. ``cd datascripts`` and run ``./get_sites.py``
3. ``docker-compose up`` and visit the sites page in the browser
4. Click on a site marker, navigate to selected site's detail page
Should be able to navigate to a selected site's detail page through use of site markers.
@LyonesGamer What is the javascript submit_map() function? You made the change in a previous merge, so I'm curious as to where it came from (since I can't find any info on it).

Fix site marker navigation

---

streamwebs_frontend/streamwebs/templates/streamwebs/base.html
streamwebs_frontend/streamwebs/templates/streamwebs/navigation.html
streamwebs_frontend/streamwebs/templates/streamwebs/sites.html
streamwebs_frontend/streamwebs/tests/models/test_user_model.py

Fixes #186
2. Go to `http://localhost:8000/streamwebs/sites/`
3. Change the language
You should see the language button on the upper left side. When changing language, the site markers should not disappear.
@osuosl/devs

Language menu fixes

---

streamwebs_frontend/streamwebs/forms.py
streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/canopy_cover_edit.html
streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/canopy_cover_view.html
streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/macroinvertebrate_edit.html
streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/macroinvertebrate_view.html
streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/riparian_transect_edit.html
streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/riparian_transect_view.html
streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/water_quality.html
streamwebs_frontend/streamwebs/tests/forms/test_cc_form.py
streamwebs_frontend/streamwebs/tests/forms/test_transect_forms.py
streamwebs_frontend/streamwebs/tests/forms/test_wq_form.py
streamwebs_frontend/streamwebs/views.py

Fixes point 4 of #187.
1. Look at the canopy cover, riparian transect, and water quality datasheets.
The site fields will be limited to the current site.
@osuosl/devs

Set datasheets to only show the selected site.

---

runtests.sh
streamwebs_frontend/streamwebs/__init__.py
streamwebs_frontend/streamwebs/apps.py
streamwebs_frontend/streamwebs/signals.py
streamwebs_frontend/streamwebs/templates/streamwebs/navigation.html
streamwebs_frontend/streamwebs/tests/perms/test_admin_group_perms.py
streamwebs_frontend/streamwebs/tests/views/test_index_view.py

fixes issue #192 
Running tests:
1. ``docker-compose run web bash``
2. ``cd streamwebs_frontend``
3. ``python manage.py test streamwebs/tests/*``
Viewing in-browser:
4. ``docker-compose up``
5. ``python manage.py createsuperuser``
6. Go to localhost:8000 in your browser; take note of the default navigation bar.
7. Logout and go to localhost:8000/admin in your browser; assign yourself to the ``admin`` group.
7. Go back to localhost:8000 and login again. Notice the navigation bar now has an extra "admin" tab that drops down to review three placeholder links for uploading resources, promoting other users to the admin group, and viewing the report page. 
```
[root@ff504cd2ac7c streamwebs_frontend]# python manage.py test streamwebs/tests/*
admin …
```

add extra "admin" tab in navigation bar viewable only to admins

---

streamwebs_frontend/streamwebs/static/streamwebs/js/graphs/macros.js
streamwebs_frontend/streamwebs/static/streamwebs/js/graphs/water_quality.js

Fixes #222.
2. Look at the water quality graphs for the Amazon Creek site
3. Look at the macroinvertebrate graphs for the Shafer Creek site
* All graphs for Amazon Creek should have full axes and labels that don't overlap, regardless of time scale or whether the graph has data
* All graphs for Shafer Creek should have sufficient spacing between labels regardless of time scale
@osuosl/devs
**Hint**: If you add ``?w=1`` to the URL when viewing the diff of this PR, it ignores the whitespace changes and gives you a more readable diff.

Fix graph widths and invalid values and ranges.

---

streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/camera_point_add.html
streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/canopy_cover_edit.html
streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/macroinvertebrate_edit.html
streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/photo_point_add.html
streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/riparian_transect_edit.html
streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/soil_edit.html
streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/water_quality.html

The @login_required decorator in views.py means that if the user isn't logged in, it automatically redirects to the login page, so these checks are unnecessary.
Fixes #232.
1. ``docker-compose up``
2. Add data to a site via the various edit views.
All of the pages should still correctly display and add data as before, or redirect to the login page if not logged in.
@osuosl/devs

Remove auth checks from templates.

---

streamwebs_frontend/streamwebs/static/streamwebs/js/graphs/water_quality.js
streamwebs_frontend/streamwebs/templates/streamwebs/graphs/water_quality.html
streamwebs_frontend/streamwebs/urls.py
streamwebs_frontend/streamwebs/views.py

Fixes #226.
2. Visit the WQ graphs for a site with good data (e.g. SE Belmont)
3. Add the data from another site (e.g. Cox Creek)
The graphs display side-by-side of each other.
@osuosl/devs

Compare WQ data between two sites at the same time.

---

streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/canopy_cover_edit.html
streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/canopy_cover_view.html

Fixes #211 
2. Go to a site and try adding Canopy Cover Survey data
There should be two cardinal boxes per row, and if you shrink your browser it should collapse into a single column.
@osuosl/devs

Fix canopy cover responsiveness

---

streamwebs_frontend/streamwebs/forms.py
streamwebs_frontend/streamwebs/models.py
streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/riparian_transect_edit.html
streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/riparian_transect_view.html
streamwebs_frontend/streamwebs/tests/forms/test_transect_forms.py
streamwebs_frontend/streamwebs/tests/forms/test_zone_formset.py
streamwebs_frontend/streamwebs/tests/views/test_rip_transect_edit_view.py
streamwebs_frontend/streamwebs/views.py

fixes issue #210 
1. Run tests
2. Load or create Site and School data as needed. Then go to http://localhost:8000/sites/[site-slug]/transect/edit/
3. Provide valid data for the general part of the main riparian transect form. For the zones table, try the following cases: 1) completely blank, where each zone has all 0s and no comments; 2) blank, where each zone has all 0s but some may have comments; 3) almost blank, with four zones completely blank and one zone with one nonzero numerical value. The first two cases should prevent form submission and print an error (see Expected Output), and the third case should allow you to submit the form successfully.
4. Check the database to verify your objects were created as expected-- for each riparian transect object created, 5 zones with its ID are …

enforce creation of all 5 zones per valid riparian transect

---

.travis.yml
dockerfiles/Dockerfile
requirements.txt
streamwebs_frontend/streamwebs/forms.py
streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/water_quality.html

Fixes #244.
1. Run the tests.
2. View the add Water Quality data page.
Tests should pass and the page should have horizontal radio buttons.
@osuosl/devs

Fix horizontal radio buttons for Django 1.11.

---

streamwebs_frontend/streamwebs/templates/streamwebs/site_detail.html

Fixes #243.
2. http://localhost:8000/sites/bottom-creek-streambank-instream-wood/
The layout should be correct and it should say "No data in this site" without any pagination buttons.
@osuosl/devs

Don't show pagination if there is no data.

---

requirements.txt
streamwebs_frontend/streamwebs/forms.py
streamwebs_frontend/streamwebs/signals.py
streamwebs_frontend/streamwebs/templates/streamwebs/admin/user_promo.html
streamwebs_frontend/streamwebs/templates/streamwebs/base.html
streamwebs_frontend/streamwebs/templates/streamwebs/navigation.html
streamwebs_frontend/streamwebs/tests/forms/test_admin_promotion_form.py
streamwebs_frontend/streamwebs/tests/perms/test_admin_group_perms.py
streamwebs_frontend/streamwebs/tests/views/test_admin_promo_view.py
streamwebs_frontend/streamwebs/tests/views/test_index_view.py
streamwebs_frontend/streamwebs/tests/views/test_resource_upload.py
streamwebs_frontend/streamwebs/tests/views/test_stats_view.py
streamwebs_frontend/streamwebs/urls.py
streamwebs_frontend/streamwebs/views/general.py

fixes issue #242 
This view:
further TODO:
1. run tests: ``docker-compose run web bash`` and ``cd streamwebs_frontend`` ``python manage.py test streamwebs/tests*``
2. Make sure your migrations current and have been applied. I usually nuke 0001 and remake it to do this.
3. Create a superuser: ``python manage.py createsuperuser``
4. Load in test users if not already present: ``cd ../data_scripts`` and ``./get_schools.py`` and ``./get_users.py``
5. ``docker-compose up`` and go to http://localhost:8000/user-promotion/
6. Go wild
7. Try logging in as a user you have changed and verify that you can/can't perform the relevant actions, like viewing the stats page or the upload resources page
8. Also verify that viewing the user promotion page is impossible if you're not logged in/not logged in as …

super admin user promotion

---

streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/camera_point_add.html
streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/camera_point_view.html
streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/canopy_cover_edit.html
streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/canopy_cover_view.html
streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/macroinvertebrate_edit.html
streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/macroinvertebrate_view.html
streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/photo_point_add.html
streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/photo_point_view.html
streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/riparian_transect_edit.html
streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/soil_edit.html
streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/soil_view.html
streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/water_quality.html

Removed 'added' checks in edit/view templates, added messages to view-templates
fixes issue #252 
1. Run the webserver locally
2. Add a new datasheet to a site
3. Check to see that the page redirects to the view, and the view displays the correct message
@osuosl/devs

Code cleanup, datasheet submission messages

---

streamwebs_frontend/streamwebs/templates/streamwebs/graphs/macroinvertebrates.html

fixes issue #306 
1. Look at macro graph.
2. See no time selectors.
3. Example: http://localhost:8000/sites/bear-creek/macros
@osuosl/devs

Remove macro graph time selectors

---

streamwebs_frontend/streamwebs/static/streamwebs/js/sites.js
streamwebs_frontend/streamwebs/templates/streamwebs/sites.html

fixes issue #314 
1. Fire up localhost:8000
2. Navigate to maps (you may need to change api key in sites.html to get map to show)
3. Search Sites
4. See that sites are added or removed based on search, regardless of case
```
This map search works
```
@osuosl/devs

Search sites now populates map with only relevant markers (to search)

---

docs/source/conf.py
docs/source/index.rst

Also include the about page as it was missing.
1. cd docs
2. make html
When you view the docs it should show up using the default theme.
@osuosl/devs

Set docs theme to 'default' so that the RTD theme is used

---

streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/macroinvertebrate_view.html
streamwebs_frontend/streamwebs/views/general.py

fixes issue #348
fixes partial issue #350 (Since i had 10 minutes might as well)(The other issue fixed by Bailey)
1. Find site with data that has a good number of data, that has number of data almost divisible by ten, but adding the number of schools, will add up to that. For example, 29 data sheets, with 3 schools. if number of schools added to data sheet, then it would be 32, just over 30.
Note: if data cannot be found, create your own data. Good place to start: SE belmont 27 data, 2 schools.
2. Go to a macro_view, see if the note is present
1. After adding data, the data is present in the pagination.
2. The macro_view is present.
```
$ make test
```
@osuosl/devs

Added fix to site_detail pagination

---

streamwebs_frontend/streamwebs/forms.py
streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/macroinvertebrate_edit.html
streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/macroinvertebrate_view.html
streamwebs_frontend/streamwebs/templates/streamwebs/sites.html
streamwebs_frontend/streamwebs/views/general.py

fixes issue #350 #368 
1. Navigate to shafer creek or any site
2. Add a macro invertebrate datasheet 
3. See that 'Sensitive/Intolerant' is now 'Sensitive' (first col)
4. Add some field notes
5. After adding, see that number 4 is present in viewing
6. See that field notes behave more normally now.
1. Add or edit a site -- change site name
2. Check site dropdown to see that the name of the edited site is in it's respective place in the list.
```
All these things above work!
```
@osuosl/devs

fixes sensitive/intolerant, and site sorting, and field notes view

---

streamwebs_frontend/streamwebs/views/general.py

fixes issue #xx
1. Go to a site that has rip datasheets, or add a rip datasheets, see if the export dropdown has rip
1. It has
```
$ make test
```
@osuosl/devs

Fixed riparian export button

---

dockerfiles/Dockerfile

Fixes ``docker-compose build`` problems I was running into
- Points to using our mirrors so things are faster
- Use workaround to get npm installed via epel
- Remove unnecessary yum upgrade which breaks the build
@osuosl/devs

Dockerfile fixes

---

streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/rip_aqua_edit.html
streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/rip_aqua_view.html

fixes issue #447 
1. Go to a site, add riparian aquatic survey
2. See the back button in the upper left
3. See teal text instead of blue
4. Add datasheet -> repeat steps 2 and 3
```
$ make test
```
@osuosl/devs

Added back button, removed blue text. Replaced with teal

---

data_scripts/get_additional_wq.py
data_scripts/get_all.sh
data_scripts/get_cc.py
data_scripts/get_macros.py
data_scripts/get_required_fields.py
data_scripts/get_schools.py
data_scripts/get_sites.py
data_scripts/get_soil.py
data_scripts/get_transects.py
data_scripts/get_users.py
data_scripts/get_wq_basic.py
data_scripts/rename_schools.py
data_scripts/set_schools.py
data_scripts/set_tools.py
data_scripts/update-csvs.sh

Partially fixes issue #461 
This required updating data directly on the current Drupal website to fix some importing issues that were manually fixed with the csv data before. Once this is merged then we can update the data in the ansible side.
1. ``cd csvs``
2. ``../data_scripts/update-csvs.sh``
3. ``cd ..``
4. ``docker-compose kill && docker-compose rm --all -f``
5. ``docker-compose up -d postgres_host``
6. ``docker-compose up`` After migrations have run, exit
7. ``docker-compose run web bash``
8. ``cd data_scripts``
9. ``./get_all.sh``
10. Exit out of container and run ``docker-compose up``
You should see newly added sites, and other data.

Add script to automate updating the CSV data from the Drupal site

---

.gitignore
data_scripts/pull-files.sh

1. ``cd data_scripts``
1. ``./pull-files.sh``
Should run without any errors and you should also see symlinks like this:
``` console
$ pwd
/home/centos/streamwebs
$ ls -l streamwebs_frontend/media/
total 0
lrwxrwxrwx 1 root root 22 Oct 24 16:18 pp_photos -> ../../media/pp_photos/
lrwxrwxrwx 1 root root 24 Oct 24 16:18 site_photos -> ../../media/site_photos/
```

Media path fixes

---

streamwebs_frontend/streamwebs/static/streamwebs/js/sites.js
streamwebs_frontend/streamwebs/templates/streamwebs/sites.html

fixes #515 
1. Go to http://localhost:8000/sites/
2. Click on a site
You should see the map working properly again and when you click on a site, you should see a truncated description of 50 words or less.
@hertelc I also have this running at http://streamwebs-dev.osuosl.org:8000/ if you want to check yourself.

Escape the site.description for javascript and truncate

---

.travis.yml
README.md
dockerfiles/Dockerfile.env.dist
dockerfiles/cleanup.sh
dockerfiles/startup.sh
runtests.sh

This applies a few enhancements and fixes for the docker-compose development environment.
1. ``docker-compose kill && docker-compose rm --all -f``
1. ``docker-compose up`` -- this should run without any issue
Keep in mind to remove the setting var after each test for below:
1. Add `` STREAMWEBS_DROP=1`` to ``dockerfiles/Dockerfile.env``
1. ``docker-compose stop web && docker-compose up web`` should now drop the database and run migrations again
1. Add `` STREAMWEBS_TEST=1`` to ``dockerfiles/Dockerfile.env``
1. ``docker-compose stop web && docker-compose up web`` should now only run tests
1. Add `` STREAMWEBS_DROP=1`` and ``STREAMWEBS_IMPORT_DATA=1`` to ``dockerfiles/Dockerfile.env``
1. ``docker-compose stop web && docker-compose up web`` should now drop the database and import the CSV …

Improve docker-compose environment

---

streamwebs_frontend/streamwebs/templates/streamwebs/base.html
streamwebs_frontend/streamwebs/templates/streamwebs/create_site.html
streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/camera_point_add.html
streamwebs_frontend/streamwebs/templates/streamwebs/datasheets/camera_point_view.html
streamwebs_frontend/streamwebs/templates/streamwebs/sites.html
streamwebs_frontend/streamwebs/templates/streamwebs/update_site.html

This should resolve mixed content warnings when using the site over https. This
is related to #546. Hopefully I found all situations where this is happening!
**Testing this PR will be difficult since it requires a fully functioning SSL pathway. It's best to test this first on staging once deployed.**
1. Open each url below and open up the developer console for your browser
2. You should not see any warnings about mixed content from our browser
- https://streamwebs-staging.osuosl.org/
- https://streamwebs-staging.osuosl.org/sites/
- https://streamwebs-staging.osuosl.org/sites/new/
- https://streamwebs-staging.osuosl.org/sites/se-belmont/edit/
- https://streamwebs-staging.osuosl.org/sites/se-belmont/camera/edit/
- https://streamwebs-staging.osuosl.org/sites/se-belmont/camera/1812/
You …

Use https for all google api content

---

streamwebs_frontend/streamwebs/templates/streamwebs/admin/stats.html
streamwebs_frontend/streamwebs/views/general.py

fixes issue #624 
1. Navigate to the stats page. 
2. Select today
3. See results from today as well.
4. Enjoy the fancy lists.
```
$ make test
```
@osuosl/devs

(bugfix/statsfix) When user selects today for stats, it now shows the stats from the day.

---

streamwebs_frontend/streamwebs/migrations/0035_editor_access.py

This PR disables the editor access migration (0035_editor_access.py) to avoid setting all users to editor access should the production system have migration run on it again.
This migration probably should have been a stand alone file that was manually run on production, but instead it made it into the develop branch.

Disable editor access migration

---

requirements.txt
streamwebs_frontend/streamwebs_frontend/settings.py.dist

This adds support for https://sentry.io so that we can manage our application
errors in a more sane fashion. For it to actually work, you need to setup
projects on an account which we'll do on the OSL side. But for general
development this doesn't require anything.
You will need to rebuild your web docker image to test and use this since we
import the raven (Sentry's python library) in settings.py.
This resolves partially #652

Add Sentry.io reporting

---

streamwebs_frontend/streamwebs/templates/streamwebs/resources.html

fixes issue #649 
1. Go to resource page
2. See that "upload a new resource" button is gone (must be admin)
3. See educator kits button is gone
```
$ make test
```
@osuosl/devs

removed educator kits and upload resource

---

streamwebs_frontend/streamwebs/static/streamwebs/js/site_detail.js

fixes issue #645 #648
1. Load up Edge
2. Go to Site Detail, logged in as admin
3. See Gallery Items, datasheet items, drop downs working
@osuosl/devs

Edge pages now display gallery and datasheets, drop downs work
